apiVersion: 1

datasources:
  - name: cloudwatch
    type: cloudwatch
    access: proxy
    uid: cloudwatch
    isDefault: true
    jsonData:
      authType: ec2IAMRole
      defaultRegion: ${AWS_DEFAULT_REGION:eu-central-1}
    editable: true

